extra-deps:
  - ghcjs-dom-0.2.4.0
  - ref-tf-0.4.0.1
  - zenc-0.1.1
  - containers-0.5.7.1
packages:
  - '.'
  - extra-dep: true
    location:
        git: https://github.com:/jonathanknowles/reflex
        commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3
  - extra-dep: true
    location:
        git: https://github.com:/jonathanknowles/reflex-dom
        commit: fca15fd1b8a2dd34e53994553907f648091c7870


resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9



